name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]


premissions:
    contents: read


concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true
   
jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
          - uses:   actions/checkout@v7
          
          - uses: actions/setup-dotnet@v6
          with:
            global-json-file: global.json
            
          - name: Restore
            run: dotnet restore TheProject.slnx
            
          -name: Check formatting
           run: dotnet format TheProject.slnx --verify-no-changes --no-restore
           
          -name: Build
           run: dotnet build TheProject.slnx --configuration Release --no-restore
           
          -name: Test
          run: dotnet test --solution TheProject.slnx --configuration Release --no-build